pipeline {
    agent any

    parameters{
        choice(
            choices: ["FantasticFarmer", "DungeonDigger", "GravelGobler"], 
            description: "Application", 
            name: "appName"
        )
        string(
            defaultValue: "1.0.0", 
            description: "Application version", 
            name: "appVersion"
        )
        booleanParam(
            defaultValue: false, 
            description: "Release?", 
            name: "doRelease"
        )
        choice(
            choices: ["debian8","rhel8", "ubuntu24"], 
            description: "Base image", 
            name: "dockerBaseImage"
        )
    }

    environment{
        def dockerBaseUri = "https://acme.corp/dockerhub/"
        def platform = "x86"
    }

    stages{
        stage("Print environment") {
            steps {
                echo "image name: ${dockerBaseUri}${params.appName}_${appVersion}_${params.dockerBaseImage}_${platform}:${env.BUILD_NUMBER}"
            }
        }
    }
}
