pipeline {
    agent any

    parameters{
        choice(
            choices: ["FantasticFarmer", "DungeonDigger", "GravelGobler"], 
            description: "Application", 
            name: "appName"
        )
        string(
            defaultValue: "1.0.0", 
            description: "Application version", 
            name: "appVersion"
        )
        booleanParam(
            defaultValue: false, 
            description: "Release?", 
            name: "doRelease"
        )
        choice(
            choices: ["docker-image-a","docker-image-b", "docker-image-c"], 
            description: "Instance type", 
            name: "instanceType"
        )
    }

    environment{
        def dockerBaseUri = "https://acme.corp/dockerhub/"
        def appExtension = "rpm" 
        def platform = "x86"
    }

    stages{
        stage("Print environment") {
            steps {
                echo "Docker url: ${dockerBaseUri}${params.appName}_${appVersion}_${platform}.${appExtension}"
            }
        }
    }
}
